### ISSUE TITLE
Missing flex-grow and flex-shrink

### ISSUE THREAD

**Issue by ciaoben** [tachyons-css/tachyons-flexbox#2] opened 2016-09-06 12:22 UTC
First of all, thanks for this great project, I am having a lot of fun using it!

I am wondering why are (imho) useful properties like `flex-grow` and `flex-shrink` missing.

If it is not a "philosophical" choice I could make a PR.

**Comment by philipyoungg** [comment] 2016-09-22 03:22
I've made a pull request for this feature, also with flex-nowrap. Hope it'll be merged soon!

**Comment by ixley** [comment] 2016-09-24 00:03
I am curious about these properties as well (along with `flex-basis`), but have the sense that they might have been left out because a lot of the same thing can be accomplished with a combination of `.flex-auto` (`flex: 1 1 auto;`) and `.flex-none` (`flex: none; // 0 0 auto;`). 

*If these were intentionally excluded, it would be nice to have that addressed in the documentation.

**Comment by mrkhdly** [comment] 2018-03-11 02:22
Tachyons v5 will become a monorepo so this issue is being closed, if the issue is still relevant please open an issue with the main repo https://github.com/tachyons-css/tachyons/issues/new & link to this one

**Closed as completed by mrkhdly** 2018-03-11 02:22 UTC
